- README.md
Updating the URL with more accurate tags.
> docs(readme): update konnect free trial url

- .github/workflows/pr.yml
- package.json
Should be a small fix but will help with catching lint errors.
> ci: lint before tests

- .npmrc
- package.json
- yarn.lock
Since this project is meant for yarn, this adds an error message when trying to run `npm i`
> build: advise to use yarn instead of npm (TDX-3164)

- src/assets/kongponents-theme.scss
- src/components/AuthCard.vue
- src/components/DisplayNameModal.vue
- src/components/service/sidebar/SectionReference.vue
- src/helpers/handleKongAuthElementsError.ts
- src/views/Applications/ApplicationForm.vue
- src/views/Applications/CredentialsList.vue
- src/views/ResetPassword.vue
- src/views/ServiceShell.vue
There are a few minor fixes to dark mode in here as well as cleaning up the TODO comments.
Dark Mode Improvments:
Disabled state for buttons:
Modal header and primary text color
Copy Icon color
KInput Help Text
> chore: clean comments and resolve issues [TDX-3087]

- README.md
Small addition to disable commit formatting.
> chore(docs): steps to disable commit formatting [tdx-3165]

- cypress/e2e/specs/catalog.spec.ts
This PR fixes the flaky catalog spec test
> test: fix flaky catalog spec test

- README.md
Adding some additional product details to the intro to the markdown. Also fixing some eslint complaints on one of the .vue files that prevented my push.
> Feat/readme update with new product details.

- README.md
Fix a few broken links, add UTM campaign to registration url
> updated readme links

- cypress/e2e/specs/application_registration.spec.ts
- package.json
- yarn.lock
This incorporates a breaking API/SDK change where updating an application was previously a PUT but is now a PATCH.
> chore(deps): bump sdk-portal-js

- cypress/e2e/specs/catalog.spec.ts
This PR updates service to product in the catalog spec
> test(catalog): update service to product

- vite.config.js
Reverts Kong/konnect-portal#110
> Revert "fix: prevent no .env"

- package.json
- yarn.lock
Bumps the spec-renderer package for some styling fixes in the responses containers.
> chore: bump spec renderer package for styling

- src/locales/ca_ES.ts
- src/locales/de.ts
- src/locales/es_ES.ts
- src/locales/fr.ts
- src/locales/i18n-type.d.ts
- src/locales/index.ts
> feat(i18n): catalan, german, spanish, french locales

- src/views/Applications/ApplicationForm.vue
This PR adds logic to clear out the error message when resubmitting the form. Previously, the error message would stay rendered even on resubmission.
> fix: remove error message in app form when resubmitting

- src/views/Spec.vue
> style: update classes in spec.vue for styling

- .github/workflows/merge-to-release.yml
- .github/workflows/release.yml
- .github/workflows/sync-changes.yml
- .releaserc.yaml
- README.md
- package.json
- yarn.lock
adds workflows for running semantic-release and merging
> ci: use semantic-release to generate releases and changelog

- src/views/Login.vue
Updates the styling of the button so styling gets applied from the theme.
> style(login): update styling of sso button on login view

- package.json
- src/views/Applications/ApplicationDashboard.vue
- src/views/Applications/ApplicationDetail.vue
- yarn.lock
https://konghq.atlassian.net/browse/MA-1977
Pulling in version bump from https://github.com/Kong/public-ui-components/pull/730, and fixing some typecheck issues.
> fix(analytics): keep peerDependencies in step with workspace version [MA-1977]

- package.json
- yarn.lock
Updates the spec renderer to fix a bug where if you collapse a section in the spec, the side bar does not scroll to it when clicked.
> fix: updates spec renderer to fix side nav bug

- README.md
- src/locales/README.md
- src/locales/ca_ES.ts
- src/locales/de.ts
- src/locales/es_ES.ts
- src/locales/fr.ts
- src/locales/index.ts
To avoid this kind of view :
I also translated a few french strings.
Added a readme
> fix(locales): switch untranslated strings to english

- src/components/product/Sidebar.vue
smallest PR. Tested on my portal.
> fix(spec-renderer): widen sidebar to max 330px

- cypress/e2e/specs/catalog.spec.ts
- src/components/Catalog.vue
- src/components/CatalogCardList.vue
- src/components/PaginationBar.vue
- src/views/ProductCatalogWrapper.vue
Adds pagination to the table view in catalog, instead of just the card view.
> fix: add pagination to table view in catalog

- src/assets/utilities.scss
- src/components/ActionsDropdown.vue
- src/components/ApiDocumentation/DocumentSections.vue
- src/components/AuthCard.vue
- src/components/Catalog.vue
- src/components/CatalogCardList.vue
- src/components/CatalogItem.vue
- src/components/CatalogTableList.vue
- src/components/Content.vue
- src/components/CopyButton.vue
- src/components/DisplayNameModal.vue
- src/components/ErrorWrapper.vue
- src/components/Nav.vue
- src/components/PageTitle.vue
- src/components/PaginationBar.vue
- src/components/UserDropdown.vue
- src/components/ViewSpecModal.vue
- src/components/ViewSpecRegistrationModal.vue
- src/components/product/Sidebar.vue
- src/components/product/sidebar/Section.vue
- src/components/vitals/AnalyticsMetricsCard.vue
- src/components/vitals/ChartPanel.vue
This PR refactors to remove the tailwind utility classes from components folder.
> refactor: remove tailwind utility from components

- src/constants/chartQueries.ts
https://konghq.atlassian.net/browse/MA-2049
> chore(vitals): drop meta query object

- .stylelintrc.js
- src/App.vue
- src/assets/kongponents-theme.scss
- src/assets/utilities.scss
- src/components/ActionsDropdown.vue
- src/components/ApiDocumentation/DocumentSections.vue
- src/components/AuthCard.vue
- src/components/Catalog.vue
- src/components/CatalogItem.vue
- src/components/CopyButton.vue
- src/components/DisplayNameModal.vue
- src/components/Nav.vue
- src/components/StatusBadge.vue
- src/components/UserDropdown.vue
- src/components/ViewSpecModal.vue
- src/components/ViewSpecRegistrationModal.vue
- src/components/vitals/AnalyticsMetricsCard.vue
- src/components/vitals/ChartPanel.vue
- src/main.css
- src/views/ApiDocumentationPage.vue
- src/views/Applications/ApplicationDashboard.vue
- src/views/Forbidden.vue
- src/views/NotFound.vue
- src/views/ProductShell.vue
- src/views/ResetPassword.vue
- src/views/Shell.vue
- src/views/Spec.vue
This PR removes the invalid styling variables that will eventually be removed.
NOTE: Lint will still fail as there are the theming variables still present, which will be removed in the next step that involves picking up the alpha branch.
> chore: remove invalid styling vars

- src/components/Catalog.vue
Fixes the pagination bar on catalog page not being correctly aligned.
> style: fix pagination bar alignment

- package.json
- yarn.lock
Bumps the `spec-renderer` version
> fix: bump spec renderer version

- src/components/Nav.vue
This is needed for a smoke test that uses the test id
> chore(nav): add data-testid for my-apps-item

- src/components/ViewSpecRegistrationModal.vue
- src/constants/feature-flags.ts
- src/locales/ca_ES.ts
- src/locales/de.ts
- src/locales/en.ts
- src/locales/es_ES.ts
- src/locales/fr.ts
- src/locales/i18n-type.d.ts
This adds developer managed scopes (for Auth0) if it is enabled for the org.
https://github.com/Kong/konnect-portal/assets/40131297/212604a3-decc-4f81-9eed-ccea8ba49cb6
> feat: add developer managed scopes to app reg modal

- cypress/e2e/specs/application_registration.spec.ts
- cypress/e2e/support/index.ts
- cypress/e2e/support/mock-commands.ts
- src/components/ViewSpecRegistrationModal.vue
- yarn.lock
This PR adds some tests for developer managed scopes.
> test: add tests for scope select

- src/components/ViewSpecRegistrationModal.vue
Update styling for multiselect to match Figma designs. Also updated to show selected scopes when collapsed.
> style: match multiselect scope styling to figma

- package.json
- src/components/ViewSpecRegistrationModal.vue
- src/components/product/sidebar/SectionReference.vue
- src/views/ApiDocumentationPage.vue
- src/views/ProductCatalogWrapper.vue
- src/views/Spec.vue
- yarn.lock
This PR updates the registration request to send the scopes if selected
> feat: send selected scopes in the request

- cypress/e2e/specs/application_registration.spec.ts
- src/components/ScopeBadges.vue
- src/components/ViewSpecRegistrationModal.vue
- src/locales/ca_ES.ts
- src/locales/de.ts
- src/locales/en.ts
- src/locales/es_ES.ts
- src/locales/fr.ts
- src/locales/i18n-type.d.ts
- src/views/Applications/ProductList.vue
- src/views/Spec.vue
This PR shows granted scopes for an application if they are present in the registration response.
https://github.com/Kong/konnect-portal/assets/40131297/4f78e479-05e7-4c0a-8a82-d93dc21e51f2
> feat(applications): show granted scopes if present

- package.json
- yarn.lock
Minor style fix within document viewer
> chore: bump document viewer version

- cypress/e2e/specs/application_registration.spec.ts
- cypress/e2e/support/index.ts
- cypress/e2e/support/mock-commands.ts
This is causing some of the failures in CI (as well as on `main).
> fix(tests): add mocking for granted scopes endpoint

- package.json
- yarn.lock
Includes fixes for an issue with sidebar scrolling
> chore(deps): bump spec-renderer version

- package.json
- yarn.lock
Bumps the document viewer version.
> chore: bump document viewer

- cypress/e2e/fixtures/consts.ts
- cypress/e2e/specs/application_registration.spec.ts
- cypress/e2e/specs/contextual-analytics.spec.ts
- cypress/e2e/support/utils/generateDocuments.ts
- package.json
- src/views/Applications/ApplicationDetail.vue
- src/views/Applications/ApplicationForm.vue
- src/views/MyApps.vue
- yarn.lock
Displays the correct tables for an application depending on the application's auth strategy.
> feat(app-reg-v2): display proper tables depending on auth strategy for app

- cypress/e2e/specs/application_registration.spec.ts
- src/locales/ca_ES.ts
- src/locales/de.ts
- src/locales/en.ts
- src/locales/es_ES.ts
- src/locales/fr.ts
- src/locales/i18n-type.d.ts
- src/views/Applications/ApplicationDetail.vue
- src/views/Spec.vue
This PR updates the application view to display the auth strategy information if present.
> feat: display auth strategy info in application view

- cypress/e2e/specs/application_registration.spec.ts
- src/components/ScopeBadges.vue
- src/locales/ca_ES.ts
- src/locales/de.ts
- src/locales/en.ts
- src/locales/es_ES.ts
- src/locales/fr.ts
- src/locales/i18n-type.d.ts
- src/views/Applications/ApplicationDetail.vue
- src/views/Applications/ProductList.vue
Granted scopes have been moved to the application instead of the application registration.
> refactor: show granted scopes at app level

- package.json
- yarn.lock
Reverts Kong/konnect-portal#422
> chore(deps): bump vue-router from 4.2.1 to 4.3.0 

- cypress/e2e/specs/application_registration.spec.ts
- src/components/ViewSpecRegistrationModal.vue
- src/constants/feature-flags.ts
Developer managed scopes is GA so we are removing the feature flag
> chore: remove developer managed scopes feature flag

- src/views/Applications/ApplicationForm.vue
There was an additional check in order for this to work properly with App Reg v2
> chore: populate reference_id from app on load

- src/composables/useLaunchDarkly.ts
This might fix some flake we're seeing when LD fails to load in time.
> refactor: load ld if not loaded

- src/components/ViewSpecRegistrationModal.vue
This adds a button to allow you to create a new application when there is data populated in the table.
> feat: add create app button when table data is populated

- tsconfig.json
Updates to skip lib checks for ts
> chore: update tsconfig to skipLibCheck

- cypress/e2e/specs/application_registration.spec.ts
- src/locales/en.ts
This PR updates the working for Credential Type from: "Self Managed Client Credentials" to "Self Managed"
> feat(appreg): update copy for self managed client credentials

- cypress/e2e/fixtures/consts.ts
- cypress/e2e/specs/application_registration.spec.ts
- cypress/e2e/specs/spec_renderer.spec.ts
- cypress/e2e/support/index.ts
- cypress/e2e/support/mock-commands.ts
- src/components/ViewSpecRegistrationModal.vue
- src/constants/feature-flags.ts
- src/main.ts
- src/stores/app.ts
- src/views/Applications/ApplicationDetail.vue
- src/views/Applications/ApplicationForm.vue
- src/views/MyApps.vue
- src/views/Spec.vue
This removes app reg v0 logic, as well as portal DCR logic as the application flows have been refactored.
> refactor: remove appregv0 and portal dcr logic

- package.json
- yarn.lock
Bumps to new version of kong-auth-elements.
> chore(deps): bump to new version of kong-auth-elements 2.12.1

- src/views/Spec.vue
This PR allows specs that were uploaded with YAML format to be viewed and downloaded in YAML format.
- stores the raw spec content as a ref to prevent unnecessary serialization every time the spec modal is opened. 
- raw spec content is passed directly to the modal, instead of always JSON stringifying. This preserves YAML format and allows the spec to be viewed and downloaded as YAML. 
- saves the spec extension after parsing, removing the need to parse again when downloading
> fix(spec): display and download specs in yaml format

- package.json
- yarn.lock
Update `@kong/kong-auth-elements` for proper `409` error messaging
> fix(errors): update kong-auth-elements for 409 error messaging [KHCP-12150]

- src/locales/en.ts
- src/views/Spec.vue
- Fixes width of auth strat card
- updates style of auth strat card
- changes copy of labels of auth strat card
Before:
After:
> fix(spec): fixes width of auth strat card

- package.json
- yarn.lock
Consume latest spec renderer from https://github.com/Kong/public-ui-components/pull/1578
> chore: consume latest spec renderer [KHCP-12420]

- src/views/ProductShell.vue
Always show latest version in sidebar by default
> fix(sidebar): always show latest version by default TDX-4310

- src/components/CatalogItem.vue
- src/constants/feature-flags.ts
Reverts Kong/konnect-portal#594
> Revert "fix(spec-renderer): cache bust spec loading behind FF [TDX-6432]"

- src/components/CatalogItem.vue
- src/constants/feature-flags.ts
Reverts Kong/konnect-portal#595
> Revert "Revert "fix(spec-renderer): cache bust spec loading behind FF [TDX-6432]""
