cypress/e2e/specs/catalog.spec.ts

This PR breaks up the chaining of cypress commands in catalog spec pagination tests.

test(catalog): breakup chaining in catalog pagination tests

---

cypress/e2e/specs/catalog.spec.ts
cypress/e2e/support/utils/generateProducts.ts
package.json
src/components/Catalog.vue
src/components/CatalogCardList.vue
src/components/CatalogItem.vue
src/components/CatalogTableList.vue
src/stores/product.ts
src/views/ServiceShell.vue
src/views/Services.vue
yarn.lock

Recent changes to Portal API v2 beta made the following adjustments:
- Removed `versions` and `has_documentation` from each search result
- Added `latest_version`, `version_count`, and `document_count` to each result

refactor(catalog): update search response properties

---

src/components/CatalogTableList.vue

Wraps the text in catalog list table view when description of a product is long.

style: wrap text in catalog table view for long descriptions

---

.github/workflows/github-pages.yml

This adds a deployment to github pages to resolves the UI on `konnect-portal.konghq.com`
Also add a `workflow_dispatch` in the case of gh-pages failure (happens sometimes).
Added comment in the workflow, but we should follow-up in a deployment.MD document afterward

build: deploy to github pages

---

.github/workflows/github-pages.yml
src/services/index.ts

Github Pages deployment was building bad URIs because of missing `/`

ci: add missing /

---

.github/workflows/pr.yml

Cypress seems to not be compatible with this approach. See error:
```console
success Already up-to-date.
Done in 0.56s.
/opt/hostedtoolcache/node/16.19.0/x64/bin/npx cypress cache list
No cached binary versions were found.
/opt/hostedtoolcache/node/16.19.0/x64/bin/npx cypress verify
The cypress npm package is installed, but the Cypress binary is missing.
We expected the binary to be installed here: /home/runner/.cache/Cypress/12.14.0/Cypress/Cypress
Reasons it may be missing:
- You're caching 'node_modules' but are not caching this path: /home/runner/.cache/Cypress
- You ran 'npm install' at an earlier build step but did not persist: /home/runner/.cache/Cypress
Properly caching the binary will fix this error and avoid downloading and unzipping Cypress.
Alternatively, you can run 'cypress …
```

ci: remove caching for cypress tests

---

.github/workflows/pr.yml

As we have `code-quality` job now there's no need to just in the cypress splitted job anymore

ci: move lint in code-quality step

---

src/components/CopyButton.vue

Adds truncate to copy buttons so creds don't overflow when creating dcr application.

fix(dcr): truncate show creds

---

.github/workflows/github-pages.yml

The workflow was missing the required permission for the first run when the github pages branch doesn't exist yet.

ci: proper permissions

---

.github/dependabot.yml

As there's plenty of patch releases, disabling update for those to not get a noisy ci

ci: ignore patch releases

---

.editorconfig

Adding the commonly used [editorconfig](https://editorconfig.org/) to setup the common IDE configurations for the project.

feat: .editorconfig integration

---

vite.config.js

prevent build when there's no `.env` file provided

fix: prevent no .env

---

package.json
yarn.lock

This bumps the spec-renderer version for minor styling fixes regarding the `servers` container in a spec.

chore: bump spec renderer version for styling

---

src/views/ApiDocumentationPage.vue

This PR updates the accept header to use vendored content type for fetching Documents

feat(documents): accept vendored content type

---

cypress/e2e/specs/login.spec.ts
cypress/e2e/specs/reset_password.spec.ts
src/helpers/handleKongAuthElementsError.ts

Adjust a minor piece of logic - it doesn't use code anymore, so we will just update the message based off of the returned error.

fix: adjust error handling for auth elements for v2 api (TDX-3212)

---

package.json
src/views/Applications/ApplicationForm.vue
src/views/ProductShell.vue
yarn.lock

This bumps the Konnect Portal API v2 SDK version to 1.0.0 from the previous beta version.

chore(deps): bump SDK version to 1.0.0

---

src/composables/useLaunchDarkly.ts
src/main.ts
src/stores/app.ts
src/views/Login.vue

This PR adds the ability to load the featureSet string from the portal context and load it for Launch Darkly (which is an optional dependency)

fix(LD): use featureset for ld

---

src/components/ViewSpecRegistrationModal.vue

This PR adds optional chaining to `product.name` in the registration modal component

fix(appreg): add optional chaining to product.name

---

src/views/Applications/ProductList.vue

The keys were invalid so this column was not rendering before - this is for the `unregister` button for an application's registered products.

fix(products-list): fix structure for table header

---

.env.example
package.json
src/router/index.ts
vite.config.js
yarn.lock

We want to reduce the bundle size that's sent over the wire to improve the performance of the application.
One of the lowest hanging fruit was bundle separation and dynamic importing of components for non-hot-path routes.
The other way to minify was by splitting out some of the commonly used components (i.e. `kongponents` or `kong-auth-elements` into their own bundles.
This got us from [~4100kb](https://github.com/Kong/konnect-portal/actions/runs/5512224881/jobs/10048777150#step:8:370) to [~2700](https://github.com/Kong/konnect-portal/actions/runs/5533435976/jobs/10096957616#step:6:392)
1. We didn't work to split up the spec renderer (currently the largest bundle). This will require some rework in the swagger-ui-kong-theme as well as in public-ui-components. This is important, and will be …

perf(vite): reduce bundle size via lazy-loaded routes

---

src/services/AuthApiService.ts

Requests that use the `client` directly and specify a path were using the window location as the base url instead of the api url configured in the env. This caused the GET permissions request to fail if using a proxy in a deployed environment (like with Netlify).

fix(auth): set the base url on axios client for requests that use raw paths

---

tailwind.config.js

The `tailwind.config` has a purge property that is deprecated, so the config has been refactored.

chore: update tailwind.config as purge is deprecated

---

cypress/e2e/specs/catalog.spec.ts
src/components/Catalog.vue
src/components/ViewSpecRegistrationModal.vue
src/components/product/Sidebar.vue
src/constants/feature-flags.ts
src/locales/ca_ES.ts
src/locales/de.ts
src/locales/en.ts
src/locales/es_ES.ts
src/locales/fr.ts
src/locales/i18n-type.d.ts
src/router/index.ts
src/views/ApiDocumentationPage.vue
src/views/Applications/ProductList.vue
src/views/ProductShell.vue

API Product Builder has been released in Konnect and we no longer need the "service" naming in the UI, only "product".

chore(flag): remove product naming feature flag

---

cypress/e2e/support/index.ts

This should now mock out the launchdarkly requests so they don't go to the remote URL.

fix(tests): mock LaunchDarkly requests during tests

---

cypress/e2e/fixtures/consts.ts
cypress/e2e/specs/catalog.spec.ts
cypress/e2e/specs/portal_auth.spec.ts
cypress/e2e/support/mock-commands.ts
cypress/e2e/support/utils/generateDocuments.ts
cypress/e2e/support/utils/generateProducts.ts

- Fixes tests that could generate invalid UUIDs by appending 1 or 2 digit numbers to a fixed-length uuid prefix
- Ensures that all code uses `crypto.randomUUID()` rather than the `uuid` package since `crypto` is available in all modern browsers and the `uuid` package is not an explicit dependency of `konnect-portal` (it happens to be available as a sub-dependency)

test(*): generate uuids with crypto.randomUUID

---

.github/workflows/pr.yml

Adds 'needs: code-quality' condition to test matrix. The 'tests' job should not be run if linting fails.

chore(ci): add lint and type check as required for tests

---

.github/workflows/check-pr-title.yml
.github/workflows/pr.yml
README.md
lefthook.yaml

No longer will lefthook check the commits on every commit, but instead we can control at the PR merge level.

ci: check PR title instead of commits

---

src/views/ApiDocumentationPage.vue

The CSS variable for the text color was renamed - so this value should be updated.

style: fix css variables for document viewer

---

cypress/e2e/specs/api_documentation.spec.ts
src/components/product/Sidebar.vue
src/locales/ca_ES.ts
src/locales/de.ts
src/locales/en.ts
src/locales/es_ES.ts
src/locales/fr.ts
src/locales/i18n-type.d.ts
src/views/ApiDocumentationPage.vue
src/views/Spec.vue

Updates to display an empty state for when a product version has no spec, as well as when a product has no product versions / documentation.

feat: improve empty states for spec / doc rendering

---

src/router/index.ts

This adds a check for a meta property in the router that will skip checking permissions / authorization if the `public` property exists on the route.
If you would to add a landing page (in the case that you have a private portal), you may add a new route like so:
```
{
path: '<PATH>',
name: '<ROUTE_NAME>',
meta: {
title: Route Title,
public: true
},
component: VueComponent
},
```

feat: add check for meta.public for public routes

---

src/views/ApiDocumentationPage.vue

The document viewer package was updated, but CSS variable names needed to be renamed.

fix: update variable names for document viewer

---

src/components/Catalog.vue
src/components/CatalogTableList.vue
src/views/ProductCatalogWrapper.vue

This PR fixes an issue where the catalog view is queried when switching views. In addition, this fixes the loading state for the table view.

refactor: dont query catalog if switching views

---

src/views/ProductShell.vue

The spec view would only show an error, but it should redirect to the 404 page if the spec is not found. In addition, it will not make the call to fetch documentation if there is no product.

refactor: redirect to 404 when spec is not found

---

cypress/e2e/specs/contextual-analytics.spec.ts
src/constants/feature-flags.ts
src/views/Applications/ApplicationDashboard.vue
src/views/MyApps.vue

https://konghq.atlassian.net/browse/MA-2027
Made sure that setting `VITE_ENABLE_LAUNCH_DARKLY=false` still loads all vitals' elements across all the pages (eg:  metric cards & charts)

chore(analytics): remove feature flag [MA-2027]

---

README.md

The status badge in the README was pointing to a Github action that runs on PR branches, not main. This swaps the badges to show two actions that run on main.

chore(docs): update status badges to use actions that run on main

---

cypress/e2e/specs/catalog.spec.ts
src/components/CatalogItem.vue
src/components/CatalogTableList.vue
src/stores/product.ts
src/views/ProductCatalogWrapper.vue

This hides the specification link in the catalog for a product - if there are no versions for that product.

feat: hide spec link in catalog if no versions

---

src/views/ProductShell.vue

Correctly updates the request to pass in the accept header which resolves the issue of incorrect document ordering

fix: correct document tree request header

---

src/components/Catalog.vue

Fixes the pagination bar to be aligned correctly with the tables / lists.

style: fix pagination bar catalog alignment

---

src/locales/ca_ES.ts
src/locales/de.ts
src/locales/en.ts
src/locales/es_ES.ts
src/locales/fr.ts
src/locales/i18n-type.d.ts
src/views/MyApps.vue

This PR adds searching to the table located in my apps.

feat: add search to my apps list

---

README.md
package.json
yarn.lock

You may now pass in a `themeOverrides` object to `SpecDetails`. Here is an example if you would like to override languages:
```
<SpecDetails
:theme-overrides="{
languages: [
{
prismLanguage: 'bash',
target: 'shell',
client: 'curl'
},
{
prismLanguage: 'javascript',
target: 'javascript',
client: 'xhr'
},
{
prismLanguage: 'java',
target: 'java'
},
]
}"
/>
```
The default languages are the following. They will be overridden by what you pass in to `SpecDetails`
```
languages = [
{
prismLanguage: 'bash',
target: 'shell',
client: 'curl'
},
{
prismLanguage: 'javascript',
target: 'javascript',
client: 'xhr'
},
{
prismLanguage: 'python',
target: 'python'
},
{
prismLanguage: 'ruby',
target: 'ruby'
}
]
```

chore: bump spec-renderer version to allow languages to be customized

---

src/components/Nav.vue
src/components/NavDropdown.vue

This makes it easy to create a basic custom dropdown that is similar to the user dropdown currently shown by default.
```vue
<NavDropdown
label="My Custom Dropdown"
:items="[
{
label: "Custom Item 1",
routerLink: 'custom-route-1'
}, {
label: "Custom Item 2",
onClick: () => doSomethingSpecial()
}
]"
/>
```

refactor(nav): convert user dropdown into generic reusable nav dropdown

---

src/components/ViewSpecRegistrationModal.vue
src/locales/ca_ES.ts
src/locales/de.ts
src/locales/en.ts
src/locales/es_ES.ts
src/locales/fr.ts
src/locales/i18n-type.d.ts

This PR Adjusts the styling of the Auth0 Developer Managed scopes modal:
- remove the background color
- adjust the position of the "X" close button
- left aligns and fixes overflow of selected scopes
- Changes place holder copy in the filter input to "filter..."

style(appreg): adjust style for scopes selection

---

package.json
yarn.lock

This reverts commit 7434ff35c9b92c806e22f77b8956fd54b6ce4643.

chore: revert bump vite from 4.5.0 to 5.0.10 (#342)"

---

cypress/e2e/specs/application_registration.spec.ts
cypress/e2e/support/index.ts
cypress/e2e/support/mock-commands.ts
package.json
src/constants/feature-flags.ts
src/locales/ca_ES.ts
src/locales/de.ts
src/locales/en.ts
src/locales/es_ES.ts
src/locales/fr.ts
src/locales/i18n-type.d.ts
src/views/Applications/ApplicationForm.vue
src/views/MyApps.vue
yarn.lock

Shows a banner if you have no available auth strategies, and disables the button to create / view the new app form.

feat: disable new apps if no auth strategies and display banner

---

src/views/Applications/ApplicationForm.vue
src/views/MyApps.vue

Adds loading logic so that the alert message does not display before the auth strategies have been fetched.

fix: add loading logic for auth strategies fetch

---

cypress/e2e/fixtures/consts.ts
cypress/e2e/specs/application_registration.spec.ts
src/components/ActionsDropdown.vue
src/locales/ca_ES.ts
src/locales/de.ts
src/locales/en.ts
src/locales/es_ES.ts
src/locales/fr.ts
src/locales/i18n-type.d.ts
src/views/Spec.vue

Shows information about the auth strategy if it's present for v2

feat(app-reg-v2): show auth strategy info in spec view (TDX-3718)

---

cypress/e2e/fixtures/consts.ts
cypress/e2e/specs/application_registration.spec.ts
cypress/e2e/support/mock-commands.ts
package.json
src/components/ViewSpecRegistrationModal.vue
src/views/Spec.vue
yarn.lock

This work is currently behind a feature flag. when enabled, the applications list in the product version view will only list those that match the auth_strategy_id of the product version.

feat(app-reg-v2): filter applications by auth_strategy_id

---

src/components/ViewSpecRegistrationModal.vue
src/components/product/Sidebar.vue
src/views/ProductShell.vue

This PR resolves an error with the App Reg modal when redirecting back from the create application page. In addition, it adds guards to not renderer components that rely on the product and version until they have been fetched.

fix(product): ensure product and version are available before rendering dependent components

---

src/components/ViewSpecRegistrationModal.vue

`selectedScopes` would be null if there were no `granted-scopes` returned from the response. This updates it to check for a truthy value before setting.

fix: add check for granted scopes before setting in modal

---

cypress/e2e/fixtures/consts.ts
cypress/e2e/specs/application_registration.spec.ts
cypress/e2e/support/index.ts
package.json
src/views/Applications/ApplicationDetail.vue
src/views/Applications/ApplicationForm.vue
src/views/MyApps.vue
yarn.lock

The SDK should no longer have any more `internal` flags, so this updates to the latest version of the SDK.

chore: update to latest portal sdk

---

src/views/ProductShell.vue

I believe this should fix the root of some testing flakiness. When we leave a product page and unmount the product shell, we will unset the product so that we do not have any stale state going between products.

fix(products): unset product when unmounting shell

---

.github/dependabot.yml

This reverts commit 71dcf09ee0eb51b63c3ccb6b0c41a77a93a9ec57.
There was a [schema complaint](https://github.com/Kong/konnect-portal/runs/22309197813) in CI on merge:
```
The property '#/updates/0/' contains additional properties ["grouped-dependencies"] outside of the schema when none are allowed
```

ci: revert group dependabot updates

---

cypress/e2e/specs/spec_renderer.spec.ts
src/views/Spec.vue

This information should not be visible if the portal is public.

fix: hide auth strategy if public

---

src/views/Applications/ApplicationForm.vue

Show the auth strategy dropdown even if there is only one active auth strategy so that it is less confusing to the user.

chore: show auth strategy dropdown even if 1 auth strategy

---

package.json
src/locales/ca_ES.ts
src/locales/de.ts
src/locales/en.ts
src/locales/es_ES.ts
src/locales/fr.ts
src/locales/i18n-type.d.ts
src/router/index.ts
src/views/OAuth2Redirect.vue
src/views/Spec.vue
yarn.lock

This is related to this PR to investigate enabling some of the methods available for OAuth2 Try It Out Authorization in swagger-ui using our spec renderer.
Please see https://gist.github.com/andrewwylde/d47c94c7629a81a0232ac80ef862e788 for setup.

feat(swagger): handle redirects from OIDC IdP and initialize swagger

---

src/components/ViewSpecRegistrationModal.vue

This PR updates the app reg modal to hide the title while in a pending state. Previously, "No Applications" was shown briefly while the state was loading. 
The `modalText` computed property has also been refactored to incorporate the loading state logic and the `applications.length` logic which was previously defined in the template.

fix(appreg): don't show app reg modal title while state is pending

---

src/views/Spec.vue

This PR adds optional chaining on the tags array reference to prevent an uncaught error when selecting operations in the "Default" section of the sidebar. This error causes the "scroll to operation" behavior to stop working
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '0')
```

fix(spec): handle case where operation has no tags

---

package.json
yarn.lock

- Upgrades spec-renderer to 2.1.23 which includes Swagger UI version upgrade to 5.7.2
- Fixes issue with rendering multiple callbacks in swagger

chore(deps): upgrade spec-renderer to 2.1.23

---

src/views/Applications/ApplicationForm.vue

Autoselects an auth strategy is there is only one, and doesn't allow you to change it as an application needs an auth strategy.

fix: autoselect auth strategy if there is only one

---

cypress/e2e/fixtures/consts.ts
cypress/e2e/specs/application_registration.spec.ts
cypress/e2e/support/mock-commands.ts
package.json
src/locales/ca_ES.ts
src/locales/de.ts
src/locales/en.ts
src/locales/es_ES.ts
src/locales/fr.ts
src/locales/i18n-type.d.ts
src/views/ProductShell.vue
src/views/Spec.vue
yarn.lock

Disables register button and adds tool tip if registration is disabled

fix(spec): disable register when disabled TDX-4796 

---

src/views/ApiDocumentationPage.vue

Applies block and margin to list item paragraphs in markdown documents

fix(markdown): add styling to li paragraphs

---

src/router/index.ts
src/router/route-utils.ts

When passing a route to the `next` callback with an object that looks like `{path: string}`, the hash is not included. When the hash is included in the redirect, then, it would continually compare the path to the redirectPath, and they would not match (one would be missing the hash). Therefore it would cause an infinite redirect loop causing a crash/OOM.
By checking for a hash and passing it along to the `next` callback, it allows correct comparison, and redirects properly.

fix: login redirect was not handling hash

---

cypress/e2e/specs/api_documentation.spec.ts
package.json
src/constants/feature-flags.ts
src/views/ApiDocumentationPage.vue
yarn.lock

Replaces current markdown viewer with  @kong/markdown  
One issue I noticed is non-text headings TOC does not work, for example if the heading is a code format

feat(doc): switch to @kong/markdown TDX-4186

---

cypress/e2e/specs/login.spec.ts
cypress/e2e/specs/register.spec.ts
src/main.ts

This PR adds logic to read `saml_auth_enabled` to determine if the SSO login button should be enabled

feat(auth): read saml auth enabled flag from portal context
